# Generated by Django 5.0.1 on 2024-01-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_comment_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='author',
            new_name='writter',
        ),
    ]
